spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectpractice3
    username: root
    password: lzy3122588
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: lzy3122588
mybatis-plus:
  mapper-locations: classpath:/a/mapper/*.xml
  type-aliases-package: com.lzy.a.entity
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 1000
  global-config:
    db-config:
      id-type: auto
